name: publish
on:
  push:
    branches:
      - master
    # Build image whenever a file under src/ is changed
    paths:
      - 'src/**'
      - '.github/workflows/docker-build.yaml'
      - 'package*.json'
      - 'npm-shrinkwrap.json'
      - 'yarn.lock'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: devlaunchers/site-projects # list of Docker images to use as base name for tags
          # generate Docker tags based on the following events/attributes
          # flux image update policy sorts by timestamp
          tags: |
            type=raw,value={{sha}}-${{ steps.date.outputs.date }}
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

