name: release
on:
  push:
    branches:
      - release
    paths-ignore:
      - 'staging/flux-patch.yaml'
      - 'production/flux-patch.yaml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Release
        env:
          # Events triggered by the GITHUB_TOKEN will not create a new workflow, as a workaround we can call the env GH_TOKEN
          # https://github.com/semantic-release/github accepts GH_TOKEN and GITHUB_TOKEN
          # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: npx semantic-release
