import { onboardingActions } from ".";

const SHOW_PLATFORM_ONBOARDING_MODAL = "SHOW_PLATFORM_ONBOARDING_MODAL";
const HIDE_PLATFORM_ONBOARDING_MODAL = "HIDE_PLATFORM_ONBOARDING_MODAL";
const SHOW_INTRODUCTION_MODAL = "SHOW_INTRODUCTION_MODAL";
const HIDE_INTRODUCTION_MODAL = "HIDE_INTRODUCTION_MODAL";
const HIDE_ALL_MODALS = "HIDE_ALL_MODALS";
const SET_USERS_ROLE = "SET_USERS_ROLE";
const SET_USERS_EXPERIENCE = "SET_USERS_EXPERIENCE";
const SET_USERS_INTEREST = "SET_USERS_INTEREST";
const REMOVE_USERS_INTEREST = "REMOVE_USERS_INTEREST";
const HIDE_CLOSING_MODAL = "HIDE_CLOSING_MODAL";
const SHOW_CLOSING_MODAL = "SHOW_CLOSING_MODAL";
 
export {
    SHOW_PLATFORM_ONBOARDING_MODAL,
    HIDE_PLATFORM_ONBOARDING_MODAL,
    SHOW_INTRODUCTION_MODAL,
    HIDE_INTRODUCTION_MODAL,
    HIDE_ALL_MODALS,
    SET_USERS_ROLE,
    SET_USERS_EXPERIENCE,
    SET_USERS_INTEREST,
    HIDE_CLOSING_MODAL,
    SHOW_CLOSING_MODAL,
} 

