const SHOW_OVERVIEW_SETTING = 'SHOW_OVERVIEW_SETTING';
const HIDE_OVERVIEW_SETTING = 'HIDE_OVERVIEW_SETTING';

const SHOW_PROJECTS_SETTING = 'SHOW_PROJECTS_SETTING';
const HIDE_PROJECTS_SETTING = 'HIDE_PROJECTS_SETTING';

const SHOW_PROFILES_SETTING = 'SHOW_PROFILES_SETTING';
const HIDE_PROFILES_SETTING = 'HIDE_PROFILES_SETTING';

const SHOW_IDEAS_SETTING = 'SHOW_IDEAS_SETTING';
const HIDE_IDEAS_SETTING = 'HIDE_IDEAS_SETTING';

const SHOW_OPPORTUNITIES_SETTING = 'SHOW_OPPORTUNITIES_SETTING';
const HIDE_OPPORTUNITIES_SETTING = 'HIDE_OPPORTUNITIES_SETTING';

const SHOW_CHATBOT_SETTING = 'SHOW_CHATBOT_SETTING';
const HIDE_CHATBOT_SETTING = 'HIDE_CHATBOT_SETTING';

export {
  SHOW_OVERVIEW_SETTING,
  HIDE_OVERVIEW_SETTING,
  SHOW_PROJECTS_SETTING,
  HIDE_PROJECTS_SETTING,
  SHOW_PROFILES_SETTING,
  HIDE_PROFILES_SETTING,
  SHOW_IDEAS_SETTING,
  HIDE_IDEAS_SETTING,
  SHOW_OPPORTUNITIES_SETTING,
  HIDE_OPPORTUNITIES_SETTING,
  SHOW_CHATBOT_SETTING,
  HIDE_CHATBOT_SETTING,
};
