---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-website
  namespace: platform-website
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: platform-website
      containers:
      - image: devlaunchers/platform-website:sha-1855252
        name: platform-website
