apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: site-projects-staging
  name: site-projects
spec:
  template:
    spec:
      containers:
      - name: site-projects
        image: devlaunchers/site-projects:latest
        ports:
        - containerPort: 3000