apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: site-projects-staging
bases:
- ./kservice.yaml
images:
- name: devlaunchers/site-projects
  newName: devlaunchers/site-projects
  newTag: "079ab53-202207212256" # {"$imagepolicy": "site-projects-staging:site-projects:tag"}
