apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: recruiting-staging
  name: recruiting
spec:
  template:
    spec:
      containers:
      - name: recruiting
        image: devlaunchers/dev-recruiters:latest
        ports:
        - containerPort: 3000