apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strapiv4
bases:
- ../workload
- ./configmap.yaml
images:
- name: devlaunchers/strapi
  newName: devlaunchers/strapi
  newTag: 1.5.0 # {"$imagepolicy": "strapiv4:strapi:tag"}
