apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-website-staging
resources:
- kservice.yaml
images:
  - name: devlaunchers/platform-website
    newName: devlaunchers/platform-website
    newTag: 5e1e95d-202111152306 # {"$imagepolicy": "platform-website:platform-website:tag"}
