import React from "react";
import constate from "constate"; // State Context Object Creator

import createData from "../content/collections/createData.json";
import learnData from "../content/collections/learnData.json";

// Built from this article: https://www.sitepoint.com/replace-redux-react-hooks-context-api/

// Step 1: Create a custom hook that contains your state and actions
function useSheets() {
  const [learnPageData, setLearnPageData] = React.useState({});
  const [createPageData, setCreatePageData] = React.useState({});

  // sheetsDataToPageJSON() converts data from our google sheets format to our expected JSON format
  //  - when data is returned, store it in this context's state
  const sheetsDataToPageJSON = (sheetsElements) => {
    /*
     *  Converts data from a row based spreadsheet into a nested JSON object representing our page structure
     *  JSON Format:
     *    {
     *      tabName: {
     *        sectionName: {
     *          groupName: [
     *            entryObject1,
     *            entryObject2,
     *            ...
     *          ]
     *        },
     *        ...
     *      },
     *      ...
     *    }
     */
    const pageData = {};
    sheetsElements.forEach((element) => {
      if (element.isActive === "TRUE") {
        const { tab } = element;
        const { section } = element;
        const { group } = element;
        const entryData = {
          id: element.id,
          title: element.title,
          description: element.description,
          href: element.url,
          imageSrc: element.imageSrc,
          attachments: element.attachments,
        };

        // if tab doesn't exist yet, create it
        if (!(tab in pageData)) pageData[tab] = {};
        // if section in this tab doesn't exist yet, create it
        if (!(section in pageData[tab])) pageData[tab][section] = {};
        // if group in this section doesn't exist yet, create it
        if (!(group in pageData[tab][section]))
          pageData[tab][section][group] = [];

        pageData[tab][section][group].push(entryData);
      }
    });
    return pageData;
  };
  // Fetch sheets data using Tabletop when hook is initialized
  React.useEffect(() => {
    /*
    Tabletop.init({
      key: "1QV419fM2DHZM59mFK6eYYbYiq6bs4sBUpTwVZ_dZJNg",
      callback: (googleData) => {
        setLearnPageData(sheetsDataToPageJSON(googleData.learnPage.elements));
        setCreatePageData(sheetsDataToPageJSON(googleData.createPage.elements));
      },
      simpleSheet: false,
    });
    */

    setLearnPageData(sheetsDataToPageJSON(learnData));
    setCreatePageData(sheetsDataToPageJSON(createData));
  }, []);

  return { learnPageData, createPageData };
}

// Step 2: Declare your context state object to share the state with other components
const [SheetsProvider, useSheetsContext] = constate(useSheets);
export { SheetsProvider, useSheetsContext };

const createData = [
  {
    isActive: "TRUE",
    id: "platformer",
    tab: "Templates",
    section: "Games",
    group:
      "These templates use the game framework Phaser 3. Click one to begin creating!",
    title: "Platformer",
    url: "https://codesandbox.io/s/project-templateplatformer-ky2et",
    description:
      "A simple recreation of the physics involved with a basic platformer game.",
    format: "OTHER",
    imageSrc: "images/thumbnails/create/platformer.png",
    attachments: [
      {
        name: "player-sprite.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=player-sprite-a96f3fe4ba94291",
      },
      {
        name: "box.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=box-7486756e98ec2d2",
      },
      {
        name: "platform.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=platform-c2c4943af81ac24",
      },
      {
        name: "background.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=background-a93416d8342bdd6",
      },
    ],
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    id: "rpg",
    tab: "Templates",
    section: "Games",
    group:
      "These templates use the game framework Phaser 3. Click one to begin creating!",
    title: "RPG",
    url: "https://codesandbox.io/s/project-templaterpg-ckmzl",
    description:
      "A simple base template for an RPG with randomized environment objects, player movement, dialog, and NPCs",
    format: "OTHER",
    imageSrc: "images/thumbnails/create/rpg.png",
    attachments: [
      {
        name: "character.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=character-3d2727efa421c82",
      },
      {
        name: "npc.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=npc-331bc1b9b019816",
      },
      {
        name: "tree.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=tree-2a71d8ed9cdbab2",
      },
      {
        name: "building-outer.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=building-outer-8cde3fef30bc01d",
      },
      {
        name: "building-inner.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=building-inner-1a8ad8dbe22c3da",
      },
      {
        name: "grass.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=grass-5817f6ebda8af4a",
      },
      {
        name: "rock.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=rock-aaf7a26af739695",
      },
      {
        name: "tree-trunk.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=tree-trunk-5249fd79ebb8f82",
      },
      {
        name: "sapling.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=sapling-c91fa9f2ac8a639",
      },
    ],
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    id: "space-arcade",
    tab: "Templates",
    section: "Games",
    group:
      "These templates use the game framework Phaser 3. Click one to begin creating!",
    title: "Space Arcade",
    url:
      "https://codesandbox.io/s/project-templatespace-arcade-k84gf?fontsize=14&hidenavigation=1&module=%2Findex.js&theme=dark",
    description: "A twist on the classic space shooter genre!",
    format: "OTHER",
    imageSrc: "images/thumbnails/create/space-arcade.png",
    attachments: [
      {
        name: "ship.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=ship-9decf8d9fa13c10",
      },
      {
        name: "bullet.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=bullet-ee13a5c500745c5",
      },
      {
        name: "asteroid.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=asteroid-d1246b707fb5b2e",
      },
      {
        name: "background.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=background-0654306692104b8",
      },
    ],
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    id: "pong",
    tab: "Templates",
    section: "Games",
    group:
      "These templates use the game framework Phaser 3. Click one to begin creating!",
    title: "Pong",
    url:
      "https://codesandbox.io/s/project-template-pong-opot8?fontsize=14&module=%2Findex.js",
    description:
      "A simple recreation of the physics involved with the classic Pong game.",
    format: "OTHER",
    imageSrc: "images/thumbnails/create/pong.png",
    attachments: [
      {
        name: "ball.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=ball-ea8b00752148b48",
      },
      {
        name: "paddle.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=paddle-22cc21dc4ed84c8",
      },
      {
        name: "background.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=background-3f4ebf4d4c43d69",
      },
    ],
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    id: "virtual-pet",
    tab: "Templates",
    section: "Games",
    group:
      "These templates use the game framework Phaser 3. Click one to begin creating!",
    title: "Virtual Pet",
    url:
      "https://codesandbox.io/s/project-template-virtual-pet-1oyty?fontsize=14",
    description:
      "A simple virtual pet base project. An animal moves back and forth within the screen space, interacts with a ball, and eats food.",
    format: "OTHER",
    imageSrc: "images/thumbnails/create/virtual-pet.png",
    attachments: [
      {
        name: "pet.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=pet-d53c706bd20e671",
      },
      {
        name: "ball.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=ball-55a88f02f34217c",
      },
      {
        name: "ground.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=ground-19486aefd972506",
      },
      {
        name: "heart.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=heart-82980169526e052",
      },
      {
        name: "sky.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=sky-58a95beb4848b90",
      },
    ],
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    id: "farm-clicker",
    tab: "Templates",
    section: "Games",
    group:
      "These templates use the game framework Phaser 3. Click one to begin creating!",
    title: "Farm Clicker",
    url: "https://codesandbox.io/s/project-templatefarm-clicker-ip0vr",
    description: "Earn money. Spend money. Grow your farm!",
    format: "OTHER",
    imageSrc: "images/thumbnails/create/farm-clicker.png",
    attachments: [
      {
        name: "coin.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=coin-cc2f1268b87c16e",
      },
      {
        name: "open-shop-button.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=open-shop-button-b65fcf1756b9742",
      },
      {
        name: "shop-menu.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=shop-menu-69634c8c2355adc",
      },
      {
        name: "exit-button.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=exit-button-fb336c14437a0a2",
      },
      {
        name: "sprout.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=sprout-86f74a8fe5dc10b",
      },
      {
        name: "carrot.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=carrot-f85210bff3610a1",
      },
      {
        name: "potato.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=potato-a9a9b1a5abc727d",
      },
      {
        name: "background.png",
        href:
          "https://devlaunchers.com/#/pixilart-wrapper?pixilartId=background-657ab2f0e4fd6f1",
      },
    ],
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    id: "simple-physics-skeleton",
    tab: "Templates",
    section: "Games",
    group:
      "These templates use the game framework Phaser 3. Click one to begin creating!",
    title: "Simple Physics Skeleton",
    url:
      "https://codesandbox.io/s/project-templateone-way-joint-constraints-vdily?fontsize=14",
    description:
      "An incredibly simple example of joint constraints, limited to joints affecting each other in one direction.",
    format: "OTHER",
    imageSrc: "images/thumbnails/create/simple-physics-skeleton.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    id: "",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    id: "visual-novel",
    tab: "Templates",
    section: "Games",
    group: "Stream games!",
    title: "Visual Novel",
    url: "https://devlaunchers.com",
    description: "Code coming soon! Art is now!",
    format: "OTHER",
    imageSrc: "images/thumbnails/create/basic-app.png",
    attachments: [
      {
        name: "character.png",
        href:
          "https://www.pixilart.com/draw/visual-novel-character-fa63811294c8551",
      },
      {
        name: "location.png",
        href:
          "https://www.pixilart.com/draw/visual-novel-location-cc74b2830a0dabc",
      },
    ],
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    id: "",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    id: "basic-app",
    tab: "Templates",
    section: "Apps",
    group:
      "These app templates are using the React library. Click one to begin creating!",
    title: "Basic App",
    url:
      "https://codesandbox.io/s/project-templatesbasic-app-xfkij?fontsize=14&hidenavigation=1&theme=dark",
    description:
      "A basic React app, ready to add your own custom designs and features to!",
    format: "OTHER",
    imageSrc: "images/thumbnails/create/basic-app.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    id: "",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    id: "",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    id: "codesandbox",
    tab: "Tools",
    section: "Web Based Tools We Love",
    group: "Code",
    title: "codesandbox.com",
    url: "https://codesandbox.io/dashboard/recent",
    description: "A great online IDE",
    format: "OTHER",
    imageSrc:
      "https://res-5.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco/qwpmkxadqnli1v2cu3zc",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    id: "pixilart",
    tab: "Tools",
    section: "Web Based Tools We Love",
    group: "Design",
    title: "pixilart.com",
    url: "https://www.pixilart.com/draw",
    description: "A great online pixel art tool",
    format: "OTHER",
    imageSrc: "https://art.pixilart.com/7c7340a84ba3e86.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    id: "",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    id: "open-game-art",
    tab: "Free Assets",
    section: "Pixel Art",
    group: "Spritesheet Collections",
    title: "Open Game Art",
    url: "https://opengameart.org/",
    description:
      "A huge collections of sprites for use in your games, or as references.",
    format: "OTHER",
    imageSrc:
      "https://cdn.ilovefreesoftware.com/wp-content/uploads/2016/07/opengameart.jpg",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    id: "spriters-resource",
    tab: "Free Assets",
    section: "Pixel Art",
    group: "Spritesheet Collections",
    title: "The Spriters Resource",
    url: "https://www.spriters-resource.com/",
    description: "A huge collections of sprites you can reference!",
    format: "OTHER",
    imageSrc: "https://www.userlogos.org/files/logos/Nandoman89/TSR.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
];

const learnData = [
  {
    isActive: "TRUE",
    tab: "Code",
    section: "Code Minigames",
    group: "Novice Activities",
    title: "Loot Boxes - Variables Intro",
    url:
      "https://codesandbox.io/s/activityloot-boxesvariables-intro-kecbj?fontsize=14&module=%2FREADME.md",
    description: "Set a variable and win a prize!",
    format: "ACTIVITY",
    imageSrc: "images/thumbnails/learn/loot-boxes__variables-intro.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Code",
    section: "Code Minigames",
    group: "Novice Activities",
    title: "Virtual Pet - Integer Feeding",
    url:
      "https://codesandbox.io/s/activityvirtual-petinteger-feeding-6cvo0?fontsize=14&module=%2FREADME.md",
    description: "Learn to set numerical variables to feed a virtual pet.",
    format: "ACTIVITY",
    imageSrc: "images/thumbnails/learn/virtual-pet__integer-feeding.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Code",
    section: "Code Minigames",
    group: "Novice Activities",
    title: "Loot Boxes - Multiple Variables",
    url:
      "https://codesandbox.io/s/activityloot-boxesmultiple-variables-r4lbx?fontsize=14&module=%2FREADME.md",
    description: "Set multiple variables to win multiple prizes!",
    format: "ACTIVITY",
    imageSrc: "images/thumbnails/learn/loot-boxes__multiple-variables.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Code",
    section: "Code Minigames",
    group: "Novice Activities",
    title: "Title Screen - Sun Position",
    url:
      "https://codesandbox.io/s/activitytitle-screensun-position-bvt7z?fontsize=14&module=%2FREADME.md",
    description:
      "Learn about screen space by changing the position of the sun!",
    format: "ACTIVITY",
    imageSrc: "images/thumbnails/learn/title-screen__sun-position.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Code",
    section: "Code Minigames",
    group: "Novice Activities",
    title: "Title Screen - Customize It",
    url:
      "https://codesandbox.io/s/activitytitle-screencustomize-it-zs9xp?fontsize=14&module=%2FREADME.md",
    description: "Play around and create your very own title screen!",
    format: "ACTIVITY",
    imageSrc: "images/thumbnails/learn/title-screen__customize-it.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Code",
    section: "Code Minigames",
    group: "Novice Activities",
    title: "Stage Maker - Array Intro",
    url:
      "https://codesandbox.io/s/activitystage-makerarray-intro-hye31?fontsize=14&module=%2FREADME.md",
    description: "Modify a stage to help your character reach their goal!",
    format: "ACTIVITY",
    imageSrc: "images/thumbnails/learn/stage-maker__array-intro.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Code",
    section: "Code Minigames",
    group: "Novice Activities",
    title: "Stage Maker - Multi Dimensional",
    url:
      "https://codesandbox.io/s/activitystage-makermulti-dimensional-3e4z0?fontsize=14&module=%2FREADME.md",
    description:
      "Modify a more complex stage to help your character reach their goal!",
    format: "ACTIVITY",
    imageSrc: "images/thumbnails/learn/stage-maker__multi-dimensional.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Code",
    section: "Code Minigames",
    group: "Novice Activities",
    title: "Stage Maker - Customize It",
    url:
      "https://codesandbox.io/s/activitystage-makercustomize-it-stvqt?fontsize=14&module=%2FREADME.md",
    description: "Create your own stage using multidimensional arrays!",
    format: "ACTIVITY",
    imageSrc: "images/thumbnails/learn/stage-maker__customize-it.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Code",
    section: "Code Minigames",
    group: "Intermediate Activities",
    title: "Assembly Line - Function Intro",
    url: "https://codesandbox.io/s/activityassembly-linefunction-intro-8kebc",
    description: "Tricky functions!",
    format: "ACTIVITY",
    imageSrc: "images/thumbnails/learn/block-bots__player-vs-machine.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Code",
    section: "Code Minigames",
    group: "Intermediate Activities",
    title: "Block Bots - Player vs Machine",
    url:
      "https://codesandbox.io/s/activityblock-botsplayer-vs-machine-jzdh4?fontsize=14&module=%2FREADME.md",
    description:
      "Pit your programmable bot against a series of bots with increasing difficulty",
    format: "ACTIVITY",
    imageSrc: "images/thumbnails/learn/block-bots__player-vs-machine.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Code",
    section: "Code Minigames",
    group: "Advanced Activities",
    title: "Staircase - Array Sort",
    url:
      "https://codesandbox.io/s/activitystaircasearray-sort-rjurf?fontsize=14&module=%2FREADME.md",
    description: "Sort an array!",
    format: "ACTIVITY",
    imageSrc: "images/thumbnails/learn/staircase__array-sort.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Code",
    section: "Social Competition",
    group: "Bots",
    title: "Block Bots - Player vs Player",
    url:
      "https://codesandbox.io/s/activityblock-botsplayer-vs-player-xhc1k?fontsize=14&module=%2FREADME.md",
    description: "Pit your programmable bot against another player",
    format: "ACTIVITY",
    imageSrc: "images/thumbnails/learn/block-bots__player-vs-player.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Code",
    section: "Structured Learning",
    group: "JS Fundamentals",
    title: "Conditions",
    url: "https://www.learn-js.org/en/Conditions",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://cdn.iconscout.com/icon/premium/png-256-thumb/js-1671195-1418806.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Code",
    section: "Coding Problems",
    group: "Leetcode",
    title: "Single Number",
    url: "https://leetcode.com/problems/single-number/",
    description:
      "Given a non-empty array of integers, every element appears twice except for one. Find that single one.",
    format: "ACTIVITY",
    imageSrc: "https://leetcode.com/static/images/LeetCode_Sharing.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Code",
    section: "Coding Problems",
    group: "Leetcode",
    title: "Contains Duplicate",
    url: "https://leetcode.com/problems/contains-duplicate/",
    description:
      "Given an array of integers, find if the array contains any duplicates.",
    format: "ACTIVITY",
    imageSrc: "https://leetcode.com/static/images/LeetCode_Sharing.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Code",
    section: "Coding Problems",
    group: "Leetcode",
    title: "Roman to Integer",
    url: "https://leetcode.com/problems/roman-to-integer/",
    description: "Given a roman numeral, convert it to an integer",
    format: "ACTIVITY",
    imageSrc: "https://leetcode.com/static/images/LeetCode_Sharing.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Code",
    section: "Coding Problems",
    group: "Leetcode",
    title: "Two Sum",
    url: "https://leetcode.com/problems/two-sum/",
    description:
      "Given an array of integers, return indices of the two numbers such that they add up to a specific target.",
    format: "ACTIVITY",
    imageSrc: "https://leetcode.com/static/images/LeetCode_Sharing.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "General",
    group: "Fundamentals",
    title: "Color Theory",
    url:
      "https://medium.com/pixel-grimoire/how-to-start-making-pixel-art-6-a74f562a4056",
    description: "The basics of colors and how they work together",
    format: "LESSON",
    imageSrc: "https://miro.medium.com/max/396/1*4nuD8cIakDQ_SkrAy21GOA.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Basics",
    title: "Pixel Art Fundamentals 1",
    url: "https://www.patreon.com/posts/pixel-art-1-6971422",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/GoodFruitsPRE1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Basics",
    title: "Pixel Art Fundamentals Part 2",
    url: "https://www.patreon.com/posts/pixel-art-part-2-11225146",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/GoodFruitsPRE1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Basics",
    title: "Pixel Art Process",
    url: "https://www.patreon.com/posts/pixel-art-8107774",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/GoodFruitsPRE1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Character",
    title: "Cuteness",
    url: "https://www.patreon.com/posts/cuteness-15259004",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/All_2.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Character",
    title: "Top Down Walk Cycle",
    url: "https://www.patreon.com/posts/top-down-walk-21353953",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/All_2.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Character",
    title: "Top Down Attack",
    url: "https://www.patreon.com/posts/top-down-attack-21959820",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/All_2.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Character",
    title: "Top Down Run Cycle",
    url: "https://www.patreon.com/posts/top-down-run-7023263",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/All_2.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Character",
    title: "Character Design 1",
    url: "https://www.patreon.com/posts/character-design-7530899",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/All_2.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Character",
    title: "Slide/Roll/Dash",
    url: "https://www.patreon.com/posts/slide-roll-dash-16562907",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/All_2.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Character",
    title: "Simple Shine Tutorial",
    url: "https://www.patreon.com/posts/simple-shine-6837557",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/All_2.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Environment",
    title: "Level Design: Progression",
    url: "https://www.patreon.com/posts/level-design-7190330",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/big%20ol%20ssss.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Environment",
    title: "Vegetation Tutorial Part 1",
    url: "https://www.patreon.com/posts/vegetation-part-7416630",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/big%20ol%20ssss.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Environment",
    title: "Vegetation Tutorial Part 2",
    url: "https://www.patreon.com/posts/vegetation-part-10886532",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/big%20ol%20ssss.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Environment",
    title: "Vegetation part 3",
    url: "https://www.patreon.com/posts/vegetation-part-15480982",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/big%20ol%20ssss.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Environment",
    title: "Rock Formations",
    url: "https://www.patreon.com/posts/rock-formations-9856719",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/big%20ol%20ssss.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Environment",
    title: "Sand",
    url: "https://www.patreon.com/posts/sand-15587559",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/big%20ol%20ssss.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Environment",
    title: "Clouds",
    url: "https://www.patreon.com/posts/clouds-13744795",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/big%20ol%20ssss.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Environment",
    title: "Stars and Planets",
    url: "https://www.patreon.com/posts/stars-and-14343744",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/big%20ol%20ssss.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Environment",
    title: "Ruins Tutorial",
    url: "https://www.patreon.com/posts/ruins-tutorial-8183989",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/big%20ol%20ssss.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Environment",
    title: "Environmental Hazards",
    url: "https://www.patreon.com/posts/environmental-13569268",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/big%20ol%20ssss.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Environment",
    title: "Modern / Indoors",
    url: "https://www.patreon.com/posts/modern-indoors-16066669",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/big%20ol%20ssss.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Environment",
    title: "City Backgrounds",
    url: "https://www.patreon.com/posts/city-backgrounds-11322639",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/big%20ol%20ssss.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Environment",
    title: "Ice and Snow Tutorial",
    url: "https://www.patreon.com/posts/ice-and-snow-17113157",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/big%20ol%20ssss.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Environment",
    title: "Top Down Houses",
    url: "https://www.patreon.com/posts/top-down-houses-17397188",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/big%20ol%20ssss.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Environment",
    title: "Making Tiles",
    url: "https://www.patreon.com/posts/making-tiles-12881715",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/big%20ol%20ssss.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Animation",
    title: "Animation Planning",
    url: "https://www.patreon.com/posts/animation-7585006",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://upload.wikimedia.org/wikipedia/en/5/5a/Breakdown_of_Walk_Cycle.jpg",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Animation",
    title: "Seamless Animation Tutorial",
    url: "https://www.patreon.com/posts/seamless-7346998",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://upload.wikimedia.org/wikipedia/en/5/5a/Breakdown_of_Walk_Cycle.jpg",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Animation",
    title: "Animation Easing",
    url: "https://www.patreon.com/posts/animation-easing-8030922",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://upload.wikimedia.org/wikipedia/en/5/5a/Breakdown_of_Walk_Cycle.jpg",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Animation",
    title: "Simple Walk Cycle",
    url: "https://www.patreon.com/posts/simple-walk-14234033",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://upload.wikimedia.org/wikipedia/en/5/5a/Breakdown_of_Walk_Cycle.jpg",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Animation",
    title: "Simple Run Tutorial",
    url: "https://www.patreon.com/posts/simple-run-6914055",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://upload.wikimedia.org/wikipedia/en/5/5a/Breakdown_of_Walk_Cycle.jpg",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Animation",
    title: "Character Idle",
    url: "https://www.patreon.com/posts/character-idle-12464240",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://upload.wikimedia.org/wikipedia/en/5/5a/Breakdown_of_Walk_Cycle.jpg",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Animation",
    title: "#79 Jumping",
    url: "https://www.patreon.com/posts/79-jumping-25803471",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://upload.wikimedia.org/wikipedia/en/5/5a/Breakdown_of_Walk_Cycle.jpg",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Animation",
    title: "Modular Animation",
    url: "https://www.patreon.com/posts/modular-15160612",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://upload.wikimedia.org/wikipedia/en/5/5a/Breakdown_of_Walk_Cycle.jpg",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Animation",
    title: "Simple Attack Animation",
    url: "https://www.patreon.com/posts/simple-attack-6837623",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://upload.wikimedia.org/wikipedia/en/5/5a/Breakdown_of_Walk_Cycle.jpg",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Animation",
    title: "Death / Take Hit Tutorial",
    url: "https://www.patreon.com/posts/death-take-hit-15846738",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://upload.wikimedia.org/wikipedia/en/5/5a/Breakdown_of_Walk_Cycle.jpg",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Animation",
    title: "Quadruped walk/trot cycle",
    url: "https://www.patreon.com/posts/quadruped-walk-14012170",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://upload.wikimedia.org/wikipedia/en/5/5a/Breakdown_of_Walk_Cycle.jpg",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Visual Effects",
    title: "Dark Magic Effects",
    url: "https://www.patreon.com/posts/dark-magic-8600078",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/space1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Visual Effects",
    title: "Motion Blur",
    url: "https://www.patreon.com/posts/motion-blur-11596285",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/space1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Visual Effects",
    title: "Metals",
    url: "https://www.patreon.com/posts/metals-11859263",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/space1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Visual Effects",
    title: "Light Magic Effects",
    url: "https://www.patreon.com/posts/light-magic-8781428",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/space1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Visual Effects",
    title: "Wind/Tornado, tutorial #50!",
    url: "https://www.patreon.com/posts/wind-tornado-50-14452186",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/space1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Visual Effects",
    title: "Illumination Techniques",
    url: "https://www.patreon.com/posts/illumination-18822379",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/space1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Visual Effects",
    title: "Darkness",
    url: "https://www.patreon.com/posts/darkness-14908368",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/space1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Visual Effects",
    title: "Holograms/Ghost effect",
    url: "https://www.patreon.com/posts/holograms-ghost-17955725",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/space1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Visual Effects",
    title: "Smoke Animation",
    url: "https://www.patreon.com/posts/smoke-animation-6851636",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/space1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Visual Effects",
    title: "Breaking Objects",
    url: "https://www.patreon.com/posts/breaking-objects-15022934",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/space1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Visual Effects",
    title: "Explosions, part 1",
    url: "https://www.patreon.com/posts/explosions-part-7719254",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/space1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Visual Effects",
    title: "Glitch Effect Tutorial",
    url: "https://www.patreon.com/posts/glitch-effect-7130333",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/space1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Spaceship Propulsion Tutorial",
    url: "https://www.patreon.com/posts/spaceship-8518887",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Wings / Flying Tutorial",
    url: "https://www.patreon.com/posts/wings-flying-8869136",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Fluids / Slimes",
    url: "https://www.patreon.com/posts/fluids-slimes-9293102",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Squash and Stretch",
    url: "https://www.patreon.com/posts/squash-and-11713421",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Bullets",
    url: "https://www.patreon.com/posts/bullets-12176568",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Blood and Guts",
    url: "https://www.patreon.com/posts/blood-and-guts-13092502",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Fabric/Flags",
    url: "https://www.patreon.com/posts/fabric-flags-13288135",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Shading",
    url: "https://www.patreon.com/posts/shading-13869731",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Outlines",
    url: "https://www.patreon.com/posts/outlines-14106192",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "1-Bit",
    url: "https://www.patreon.com/posts/1-bit-14560658",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "UI: The 9-Slice",
    url: "https://www.patreon.com/posts/ui-9-slice-14798512",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Wall Slide / Wall Kick",
    url: "https://www.patreon.com/posts/wall-slide-wall-16310292",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Spaceship Design",
    url: "https://www.patreon.com/posts/spaceship-design-16838125",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Defend/Take Hit",
    url: "https://www.patreon.com/posts/defend-take-hit-17665772",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Firearm Design",
    url: "https://www.patreon.com/posts/firearm-design-18248148",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Gems",
    url: "https://www.patreon.com/posts/gems-18529700",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Resizing Pixel Art",
    url: "https://www.patreon.com/posts/resizing-pixel-19266474",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Wood Textures",
    url: "https://www.patreon.com/posts/wood-textures-19566524",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Swords!",
    url: "https://www.patreon.com/posts/swords-19905632",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Isometric part 1",
    url: "https://www.patreon.com/posts/isometric-part-1-21638316",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Top Down Tricks",
    url: "https://www.patreon.com/posts/top-down-tricks-22246917",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Impact!",
    url: "https://www.patreon.com/posts/impact-23417521",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Electricity Tutorial",
    url: "https://www.patreon.com/posts/electricity-7075305",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Water Tutorial",
    url: "https://www.patreon.com/posts/water-tutorial-7242348",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Fire Tutorial",
    url: "https://www.patreon.com/posts/fire-tutorial-7293859",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Skulls and Bones Tutorial",
    url: "https://www.patreon.com/posts/skulls-and-bones-7475695",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "<1 Pixel Movement Tutorial",
    url: "https://www.patreon.com/posts/1-pixel-movement-7652033",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Machines and Weird Tech Tutorial",
    url: "https://www.patreon.com/posts/machines-and-7800465",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Parallax and Depth",
    url: "https://www.patreon.com/posts/parallax-and-7863658",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "Miscellaneous",
    title: "Render Tricks",
    url: "https://www.patreon.com/posts/render-tricks-7947098",
    description: "",
    format: "LESSON",
    imageSrc:
      "https://opengameart.org/sites/default/files/styles/medium/public/dice_hd_preview.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Design",
    section: "Pixel Art",
    group: "GIMP",
    title: "Setting Up GIMP for Pixel Art - A GIMP Beginner Tutorial",
    url: "https://www.youtube.com/watch?v=FZ03RlQ58qM",
    description: "A video showing how to set up GIMP to create pixel art",
    format: "VIDEO",
    imageSrc:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Gimp-wilber-scalable.svg/858px-Gimp-wilber-scalable.svg.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Challenges",
    group: "Accomplish the goal set in the descriptions!",
    title: "Physics Sprite - Max Speed",
    url:
      "https://labs.phaser.io/edit.html?src=src/physics/arcade/max%20speed.js&v=3.22.0",
    description: "GOAL: Set the max speed to 500!",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Challenges",
    group: "Accomplish the goal set in the descriptions!",
    title: "Physical Sprites and Custom Collision Boundaries",
    url:
      "https://labs.phaser.io/edit.html?src=src/physics/arcade/custom%20bounds.js&v=3.22.0",
    description:
      "GOAL: Make the boxes collide with each other using the this.physics.add.collision() function ('this' is a phaser scene object)",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Custom Sprite Class",
    url:
      "https://phaser.io/examples/v3/view/game-objects/sprites/custom-sprite-class-es6",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Health Bars",
    url:
      "https://phaser.io/examples/v3/view/game-objects/graphics/health-bars-demo",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Moving Sprite With Update",
    url:
      "https://phaser.io/examples/v3/view/game-objects/sprites/moving-sprite",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Loading Multiple Sprites",
    url:
      "https://phaser.io/examples/v3/view/game-objects/sprites/multiple-sprites",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Basic Text",
    url:
      "https://phaser.io/examples/v3/view/game-objects/text/static/basic-text",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Change Text On Input",
    url:
      "https://phaser.io/examples/v3/view/game-objects/text/static/change-text",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Emojis In Game",
    url: "https://phaser.io/examples/v3/view/game-objects/text/static/emojis",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Google Webfonts",
    url:
      "https://phaser.io/examples/v3/view/game-objects/text/static/google-webfont",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Custom Webfonts",
    url:
      "https://phaser.io/examples/v3/view/game-objects/text/static/custom-webfont",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Multiline Text",
    url:
      "https://phaser.io/examples/v3/view/game-objects/text/static/multi-line-text",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Text Shadow",
    url:
      "https://phaser.io/examples/v3/view/game-objects/text/static/shadow-stroke-styles",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Stacker Game - Simple",
    url: "https://phaser.io/examples/v3/view/game-objects/shapes/stacker",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Stacker Game - Complex",
    url: "https://phaser.io/examples/v3/view/game-objects/shapes/stacker-es6",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Animated Rectangles",
    url: "https://phaser.io/examples/v3/view/game-objects/shapes/rectangle",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Isometric World",
    url: "https://phaser.io/examples/v3/view/game-objects/shapes/iso-image#",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Isometric Character",
    url: "https://phaser.io/examples/v3/view/game-objects/shapes/iso-birdie",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Shape Drawing App",
    url: "https://phaser.io/examples/v3/view/game-objects/shapes/draw",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Particle Editor",
    url:
      "https://labs.phaser.io/view.html?src=src/game%20objects/particle%20emitter/particle%20editor.js&v=3.22.0",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Custom Image Class",
    url:
      "https://phaser.io/examples/v3/view/game-objects/images/custom-image-class-es6",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Destroying An Object",
    url:
      "https://phaser.io/examples/v3/view/game-objects/images/destroy-an-image",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "HTML In Phaser - Complex",
    url:
      "https://phaser.io/examples/v3/view/game-objects/dom-element/form-input",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "HTML In Phaser - Simple",
    url:
      "https://phaser.io/examples/v3/view/game-objects/dom-element/using-a-div",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "HTML And CSS In Phaser",
    url:
      "https://phaser.io/examples/v3/view/game-objects/dom-element/css-style-object",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Draggable Container Object",
    url:
      "https://phaser.io/examples/v3/view/game-objects/container/draggable-container",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Changing Scenes",
    url: "https://phaser.io/examples/v3/view/scenes/changing-scene-es6",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "UI Scene Communication Example",
    url: "https://phaser.io/examples/v3/view/scenes/ui-scene-es6",
    description: "Box clicking game",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Milti Scene Communication (UI Example)",
    url: "https://phaser.io/examples/v3/view/scenes/registry-data-exchange-es6",
    description: "Box clicking game (red boxes)",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Complex, Draggable Scenes (Computer Desktop Emulation)",
    url: "https://phaser.io/examples/v3/view/scenes/drag-scenes-demo",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Generate Texture With Array and Strings",
    url: "https://phaser.io/examples/v3/view/textures/generate-texture",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Generating Textures With Arrays and Strings",
    url: "https://phaser.io/examples/v3/view/textures/generate-more-textures",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Barebones Spritesheet Example",
    url: "https://phaser.io/examples/v3/view/textures/sprite-sheet",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Playing Cards - Destroy On Click",
    url:
      "https://phaser.io/examples/v3/view/input/game-object/destroy-sprite-on-down-event",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Mouseover/Spritesheet Example",
    url: "https://phaser.io/examples/v3/view/input/game-object/sprite-example",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Draw Sprites With Mouse",
    url: "https://phaser.io/examples/v3/view/input/pointer/draw-sprites",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Playing Cards - Drag and Drop Into Zone",
    url: "https://phaser.io/examples/v3/view/input/zones/drop-zone",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Multitouch Piano Example",
    url: "https://phaser.io/examples/v3/view/input/multitouch/multi-touch-test",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Detect Scrolling",
    url: "https://phaser.io/examples/v3/view/input/mouse/mouse-wheel",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Highscore Name Input Using Mouse",
    url: "https://phaser.io/examples/v3/view/input/keyboard/enter-name",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Retro Leaderboard",
    url: "https://phaser.io/examples/v3/view/input/keyboard/retro-leaderboard",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Changing Mouse Cursor",
    url: "https://phaser.io/examples/v3/view/input/cursors/cute-cursor",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Asteroid Type Game Ship Physics",
    url: "https://phaser.io/examples/v3/view/physics/arcade/asteroids-movement",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: 'Accelerate To" Example',
    url: "https://phaser.io/examples/v3/view/physics/arcade/accelerate-to",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Platformer Example",
    url: "https://phaser.io/examples/v3/view/physics/arcade/basic-platform",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Physics Playground",
    url:
      "https://labs.phaser.io/view.html?src=src/physics/arcade/body%20controls.js&v=3.22.0",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Space Ship Follow Mouse Click Shoot",
    url: "https://phaser.io/examples/v3/view/physics/arcade/bullets-group",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Simple Platformer - Collision Direction",
    url:
      "https://phaser.io/examples/v3/view/physics/arcade/collision-direction",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Basic Group Collisions",
    url: "https://phaser.io/examples/v3/view/physics/arcade/collider-1",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Physics Sprite - Draggable",
    url: "https://phaser.io/examples/v3/view/physics/arcade/draggable-body",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Physics Sprites - Make Group of Objects Collide With Each Other",
    url: "https://phaser.io/examples/v3/view/physics/arcade/group-vs-self",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Physics Sprites - Huge Collision Performance Test (Neat)",
    url:
      "https://phaser.io/examples/v3/view/physics/arcade/mass-collision-test",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Physics Sprite - Move To Clicked Position",
    url:
      "https://phaser.io/examples/v3/view/physics/arcade/move-and-stop-at-position",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Physics Sprite - Move To Object",
    url: "https://phaser.io/examples/v3/view/physics/arcade/move-to",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Physics Sprite - Multiple Objects Move To Pointer",
    url: "https://phaser.io/examples/v3/view/physics/arcade/move-to-pointer",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "Phaser 3",
    section: "Random Examples",
    group: "Uncategorized",
    title: "Physics Sprite - Clean Up Scene",
    url: "",
    description: "",
    format: "",
    imageSrc: "https://phaser.io/images/github/300/sample1.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "FALSE",
    tab: "",
    section: "",
    group: "",
    title: "",
    url: "",
    description: "",
    format: "",
    imageSrc: "",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "React",
    section: "React",
    group: "Examples",
    title: "65 Game Examples With ReactJS",
    url: "https://react.rocks/tag/Game?show=80",
    description: "A large collection of games created with React",
    format: "",
    imageSrc:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/React_Native_Logo.png/800px-React_Native_Logo.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
  {
    isActive: "TRUE",
    tab: "React",
    section: "React",
    group: "Learn React",
    title: "Beginners Guide to React",
    url: "https://scrimba.com/g/glearnreact",
    description:
      "An interactive course designed to help you dive head first into React app development!",
    format: "",
    imageSrc:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/React_Native_Logo.png/800px-React_Native_Logo.png",
    attachments: "",
    extraTagsCSV: "",
    notes: "",
  },
];
