apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strapiv4-staging
bases:
- ./configmap.yaml
- ./kservice.yaml
images:
- name: devlaunchers/strapi
  newName: devlaunchers/strapi
  newTag: 85db594-202401280240 # {"$imagepolicy": "strapiv4-staging:strapi:tag"}
