name: 'Percy'
on:
  workflow_run:
    workflows: [Chromatic]
    types: [completed]

jobs:
  on-success:    
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/UI
    if: ${{ github.event.workflow_run.conclusion == 'success' }}    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Node 16.x  
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn

      - name: Percy Storybook Snapshots
        run: export scheme=https:// && export gitHash=$(git rev-parse --short HEAD) && export appID=632ca21aeea1618b7fa0bf48 && export chromaticURL=${scheme}${gitHash}--${appID}.chromatic.com && yarn percy storybook $chromaticURL
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

  on-failure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/UI
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Node 16.x  
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn

      - name: Percy Storybook Snapshots
        run: export scheme=https:// && export gitHash=$(git rev-parse --short HEAD) && export appID=632ca21aeea1618b7fa0bf48 && export chromaticURL=${scheme}${gitHash}--${appID}.chromatic.com && yarn percy storybook $chromaticURL
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
