name: 'Percy'
on:
  push:
    paths:
      - 'packages/UI/.storybook/**'
      - 'packages/UI/src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Node 16.x  
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install @percy/cli and @percy/storybook
        run: yarn add @percy/cli @percy/storybook

      - name: Storing Chromatic Storybook link into a URL
        run: export scheme=https:// && export gitHash=$(git rev-parse --short HEAD) && export appID=--632ca21aeea1618b7fa0bf48.chromatic.com && export chromaticURL=${scheme}${gitHash}${appID}
        
      - name: Percy Storybook Snapshots
        run: yarn percy storybook $chromaticURL
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
